/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#include "stm32f103x6.h"
#include "stm32f103_GPIO_driver.h"
#include "stm32f103_EXTI_driver.h"

 uint8_t IRQ_Flag = 0;

 enum CPUAcessLevel {privileged , none_privileged };

 void Switch_CPU_Access_Level(enum CPUAcessLevel  level)
 {
	 switch(level){

	 case none_privileged:
		 __asm ("mrs r3, CONTROL \n\t"
				 "orr r3,r3, #0x1 \n\t"
				 "msr CONTROL , r3");
		 break;
	 case privileged:
		 __asm("mrs r3, CONTROL \n\t"
				"lsr r3,r3,#0x1\n\t"
				 "lsl r3,r3,#0x1\n\t"
				 "msr CONTROL , r3");
		 break;
	 }
 }

void EXTI9_CALLBACK(void)
{
	IRQ_Flag = 1;
}

int main(void)
{
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();

	//Set EXTI Configuration
	EXTI_PinConfig_t EXTIConfig;
	EXTIConfig.EXTI_PIN = EXTI9PB9;
	EXTIConfig.Trigger_Case = EXTI_Trigger_RISING;
	EXTIConfig.P_IRQ_CallBack = EXTI9_CALLBACK;
	EXTIConfig.IRQ_EN = EXTI_IRQ_Enable;
	MCAL_EXTI_GPIO_Init(&EXTIConfig);
	Switch_CPU_Access_Level(none_privileged);
	Switch_CPU_Access_Level(privileged);
	IRQ_Flag = 1;

	while (1)
	{

		if(IRQ_Flag)
		{
			IRQ_Flag = 0;
		}
		else { /* Misra */ }
	}


}
